<?php
/**
 * Strategy F UUID generation.
 *
 * @package AIMultilingual
 */

declare( strict_types=1 );

namespace AIMultilingual\Block;

/**
 * Generates RFC 4122 version-4 UUIDs for block identity.
 */
final class UuidGenerator {

	/**
	 * Maximum attempts to claim a unique UUID within one document.
	 */
	public const MAX_CLAIM_ATTEMPTS = 5;

	/**
	 * Creates a new RFC 4122 version-4 UUID string.
	 *
	 * @throws \RuntimeException When validation fails on generated bytes.
	 */
	public static function v4(): string {
		$bytes    = random_bytes( 16 );
		$bytes[6] = chr( ( ord( $bytes[6] ) & 0x0f ) | 0x40 );
		$bytes[8] = chr( ( ord( $bytes[8] ) & 0x3f ) | 0x80 );

		$hex = bin2hex( $bytes );

		$uuid = sprintf(
			'%s-%s-%s-%s-%s',
			substr( $hex, 0, 8 ),
			substr( $hex, 8, 4 ),
			substr( $hex, 12, 4 ),
			substr( $hex, 16, 4 ),
			substr( $hex, 20, 12 )
		);

		if ( ! UuidValidator::is_valid( $uuid ) ) {
			throw new \RuntimeException( 'Generated UUID failed validation.' );
		}

		return $uuid;
	}

	/**
	 * Generates and claims a UUID that is unique within the current document.
	 *
	 * @param array<string, bool> $claimed  UUIDs already assigned in document order.
	 * @param callable(): string  $generator UUID factory used for each attempt.
	 * @param int|null            $attempts  Populated with attempts used when successful.
	 */
	public static function claim_unique( array &$claimed, callable $generator, ?int &$attempts = null ): ?string {
		for ( $try = 1; $try <= self::MAX_CLAIM_ATTEMPTS; $try++ ) {
			$uuid = $generator();

			if ( ! UuidValidator::is_valid_non_empty( $uuid ) ) {
				continue;
			}

			if ( isset( $claimed[ $uuid ] ) ) {
				continue;
			}

			$claimed[ $uuid ] = true;
			$attempts         = $try;

			return $uuid;
		}

		$attempts = self::MAX_CLAIM_ATTEMPTS;

		return null;
	}
}
